import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import AuthInitializer from "@/components/AuthInitializer";
import SmoothScroll from "@/components/SmoothScroll";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Noillin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className="antialiased font-sans bg-[#F1F5F9]"
      >
        <SmoothScroll>
          <AuthInitializer />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
