export enum Permission {
  CREATE_PROFILE = "CREATE_PROFILE",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  APPROVE_SIGNUP = "APPROVE_SIGNUP",
  REJECT_SIGNUP = "REJECT_SIGNUP",
  MANAGE_USERS = "MANAGE_USERS",
}
